version: "3.8"

services:
  savedate_db:
    image: mariadb:10.5
    restart: unless-stopped
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=true
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    networks:
      backend:
        aliases:
          - ${DB_HOSTNAME}
    volumes:
      - type: bind
        source: ${DATA_LOCATION}/mysql
        target: /var/lib/mysql

  savedate_redis:
    image: redis:6.0-alpine
    restart: unless-stopped
    networks:
      backend:
        aliases:
          - ${REDIS_HOSTNAME}
    # as of now, no real data is being persisted
    volumes:
      - type: bind
        source: ${DATA_LOCATION}/redis
        target: /data

  savedate_api:
    image: docker.pkg.github.com/kodasdotio/savedate-server/savedate-server:${API_VERSION}
    restart: unless-stopped
    depends_on:
      - savedate_db
      - savedate_redis
    networks:
      traefik:
      backend:
        aliases:
          - server
    healthcheck:
      disable: true 
    volumes:
      - type: bind
        source: ${SECURITY_JWT_PRIVATE_KEY_PATH}
        target: /etc/savedate/security/certs/private.key
        read_only: true
      - type: bind
        source: ${SECURITY_JWT_PUBLIC_KEY_PATH}
        target: /etc/savedate/security/certs/public.pem
        read_only: true
      - type: bind
        source: ${API_UPLOAD_DIR}
        target: /srv/savedate/upload
    labels:
      - "traefik.enable=${TRAEFIK_ENABLED}"
      - "traefik.http.routers.savedate-${INSTANCE_NAME}-api.rule=Host(`${API_SUBDOMAIN}.${HOSTNAME}`)"
      - "traefik.http.routers.savedate-${INSTANCE_NAME}-api.tls.certresolver=${TRAEFIK_TLS_PROVER}"
      #- "traefik.http.services.savedate-${INSTANCE_NAME}-api.loadbalancer.port=3000"
      - "traefik.http.routers.savedate-${INSTANCE_NAME}-api.entrypoints=websecure"
      - "traefik.docker.network=traefik"
    environment:
      - NODE_ENV=${ENVIRONMENT}
      - APP_HOSTNAME=${API_SUBDOMAIN}.${HOSTNAME}
      # - APP_PORT=80
      # Set this to default in server
      - APP_TLS_ENABLED=true
      - APP_INSTANCE_NAME=${INSTANCE_NAME}-api
      - APP_PREFIX=${API_PREFIX}
      - APP_SWAGGER_ENABLED=${API_SERVE_SWAGGER}
      - USER_EMAIL_CONFIRM=${API_REQUIRE_EMAIL_CONFIRMATION}
      # Change to default in server
      - UPLOAD_FILE_DIR=/srv/savedate/upload
      - LOGGER_CONSOLE_LEVEL=${API_LOGLEVEL}
      - APP_BEHIND_PROXY=${USE_PROXY}
      - TYPEORM_HOST=${DB_HOSTNAME}
      - TYPEORM_USERNAME=${DB_USERNAME}
      - TYPEORM_PASSWORD=${DB_PASSWORD}
      - TYPEORM_DATABASE=${DB_DATABASE}
      - TYPEORM_PORT=${DB_PORT}
      - REDIS_HOST=${REDIS_HOSTNAME}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_PORT=${REDIS_PORT}
      - CACHE_DEFAULT_TTL=${REDIS_DEFAULT_TTL}
      - SMTP_HOST=${SMTP_HOSTNAME}
      - SMTP_USERNAME=${SMTP_USERNAME}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
      - SMTP_TLS_ENABLED=${SMTP_TLS_ENABLED}
      - SMTP_FROM_NAME=${SMTP_FROM_NAME}
      - SMTP_FROM_EMAIL=${SMTP_FROM_EMAIL}
      - SMTP_PORT=${SMTP_PORT}
      - OAUTH_GOOGLE_CLIENT_ID=${OAUTH_GOOGLE_CLIENT_ID}
      - OAUTH_GOOGLE_CLIENT_KEY=${OAUTH_GOOGLE_CLIENT_KEY}

  savedate_web:
    image: docker.pkg.github.com/kodasdotio/savedate-web/savedate-web:${FRONTEND_VERSION}
    restart: unless-stopped
    depends_on:
      - savedate_api
    networks:
      traefik:
    labels:
      - "traefik.enable=${TRAEFIK_ENABLED}"
      - "traefik.http.routers.savedate-${INSTANCE_NAME}-web.rule=Host(`${HOSTNAME}`)"
      - "traefik.http.routers.savedate-${INSTANCE_NAME}-web.tls.certresolver=${TRAEFIK_TLS_PROVER}"
      - "traefik.http.routers.savedate-${INSTANCE_NAME}-web.entrypoints=websecure"
      - "traefik.docker.network=traefik"
      #- "traefik.http.services.savedate-${INSTANCE_NAME}-web.loadbalancer.port=4200"

networks:
  backend:
    name: backend
    driver: bridge
  traefik:
    external: true
